package com.shadowslice.autotntcart.mixin;

import net.minecraft.server.MinecraftServer;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * This is the unused example mixin generated by the Fabric example mod template.
 * It doesn't do anything and can be deleted along with the "required": true /
 * mixins entry in autotntcart.mixins.json if you don't need it.
 */
@Mixin(MinecraftServer.class)
public class ExampleMixin {
    @Inject(method = "loadWorld", at = @At("HEAD"))
    private void init(CallbackInfo info) {
    }
}
